### ISSUE TITLE
Avoid bonding if FCoE is enabled

### ISSUE THREAD

**Issue by maxcuttins** [xcp-ng/xcp#138]
Create a bond with FCoE enabled lead to several connection issues.
This is explained here: https://support.citrix.com/article/CTX229847

Nobody can start the pool and know that bonding is distructive, so it's quite normal to admin, to create a cluster and then suddenly after create a network bond.
This will:
- not work without any explanation leaving interface connected and network disconnected
- crash all the storage that run on that bonded network
- adding a new server to the pool will crash when network bonding is reached

This is very bad and also very dangerous for your SR.
So I guess this should be avoided and warned careffully.

The workaround should be:
1) Cast a BIG WARNING when try to create a bond if any of the host report that FCoE service is on avoiding to go on.
```
systemctl status fcoe
systemctl status xs-fcoe
```

2) Create a button in XCP-center in order to disable this service:
```
systemctl disable fcoe
systemctl disable xs-fcoe
```

**Comment by stormi** [comment]
A warning seems required indeed.

**Comment by stormi** [comment]
For 1., how is the bond created (never done it myself up to now)? Using XO ? Then an issue at https://github.com/vatesfr/xen-orchestra/issues/ would reach the appropriate team. Using `xe`? Then we could think about a way to warn there, or at least to improve the command's help.

For 2. please open an enhancement report that references this one https://github.com/xcp-ng/xenadmin/issues

Last, it would be create if you feel confident enough to create a page dedicated to bonding on the wiki, explaining what it is, how to activate it and with that important warning.

**Comment by Fohdeesha** [comment]
Was this fixed in XS/XCP-NG 7.5 and above? They are not tagged in that xenserver page. I ask because I have 4 different XCP-NG boxes in various locations all running LACP bonds, with the management interface on top of them, and have never seen these symptoms. Checking on fcoe services status and they are indeed running

**Comment by borzel** [comment]
Wiki page: https://github.com/xcp-ng/xcp/wiki/Link-Aggregation-or-Bonding-or-Etherchannel-or-Port-Aggregation-or-Teaming

**Comment by maxcuttins** [comment]
> 
> 
> Was this fixed in XS/XCP-NG 7.5 and above? They are not tagged in that xenserver page. I ask because I have 4 different XCP-NG boxes in various locations all running LACP bonds, with the management interface on top of them, and have never seen these symptoms. Checking on fcoe services status and they are indeed running

I run XCP7.6 and was not fixed.
I guess this issue is related ONLY to card that support FCoE.
My cards support FCoE (i can see in the interface tab) so they cannot accomplish the bond because the service is likely to exclusive handling the cards or something like.

If your cards doesn't support FCoE than probably is undifferent for you enable/disable this service.

**Comment by Fohdeesha** [comment]
>If your cards doesn't support FCoE than probably is undifferent for you enable/disable this service.

AH yes, that makes perfect sense. These are all Mellanox with FCoE not supported.

**Comment by luganofer** [comment]
Has this problem been resolved in the new version (XS/XCP-NG 8.0 and above)?
The problem occurs only when creating the bond?
How about if I will upgrade from XS 6.5 to XCP-NG 7 with created bonds in lacp and SR vía FCoE?

**Comment by stormi** [comment]
Hi. There was no software change related to this, but there are warnings in the documentation. For your other questions I suggest to try the forum, where you'll find many experienced and helpful users, or contact XCP-ng support if you have a subscription so that they help you with the migration (I advise XCP-ng 8.0, or 8.1 which will be released soon, rather than 7.6 which will soon be EOL).

**Comment by olivierlambert** [comment]
The thing we can do (if FCoE is reported via XAPI), is to put a BIG WARNING in bond creation view in Xen Orchestra, if FCoE is detected on the system.

**Comment by stormi** [comment]
So, according to XAPI developers, it's been impossible to create a bond on a PIF that is using FCoE since XenServer and XCP-ng 7.5.

@maxcuttins you said that it's not fixed in XCP-ng 7.6. Was the bond created in an older version of XS / XCP-ng?

I suppose the only users than can be affected now are those who had such setup before 7.5.

**Comment by olivierlambert** [comment]
We'd like to have people with HBA capable cards, because I think you don't need to connect to an HBA storage to get the problem.
