### ISSUE TITLE
XCP-NG 8.1 | [ 4.848474] efi: EFI_MEMMAP is not enabled

### ISSUE THREAD

**Issue by OhSoNoob** [xcp-ng/xcp#377]
I have been using XCP-NG 8.0 for about 6 months without any issues on my hardware, but when upgrading last week, i got some trouble.

Now, a new weekend and more time to investigate.

The issue i am facing is after the installation, it seems to boot fine until the following line comes:
[ 4.848474] efi: EFI_MEMMAP is not enabled,

After this line, it just stops.

So i tried the BIOS mode, which results in a steady blinking "__".

Tried installing XCP-NG 8.0, no issues.

Tried Alternate Kernel, same problem.

Tried updating my BIOS to the latest version (2.10 -> 2.50), same problem.

I have disconnected everything except the essentials (CPU, RAM, Motherboard and HDD)

This is my hardware:
Motherborad: ASRock B250M Pro4
CPU: Intel i5 6400
Memory: 4x 8GB DDR4 2133

**Comment by OhSoNoob** [comment]
![CFB35CB4-1C4F-452D-A989-8B49C12D3530](https://user-images.githubusercontent.com/18257466/79638939-b0cd4780-8188-11ea-808b-c857424f9bf4.jpeg)

Update: i tried installing Citrix Hypervisor 8.1, it seems to be stuck on the same point, but gives more info doing so.

**Comment by OhSoNoob** [comment]
![E2707D39-C904-4A31-B0A9-1041C411A601](https://user-images.githubusercontent.com/18257466/79640029-98acf680-818f-11ea-9e48-8e204c851a4c.jpeg)

After about 10 minutes it continues to boot and show me the Citrix Hypervisor screen. Looking in to the /var/log/kern.log it seems like it is stuck on a QLogic driver, but i al not having any QLogic NIC’s, only Intel. Right now i put back my Intel t350-4 card back in, and disabled onboard LAN in the BIOS, nu luck. I will reinstall XCP-NG 8.1 now and check what i get there after waiting for a while.

**Comment by olivierlambert** [comment]
You probably have the NTP systemd bug (Chrony waiting 10 minutes before timing out if it can't reach the NTP server).

This is fixed in our updates.

**Comment by OhSoNoob** [comment]
> You probably have the NTP systemd bug (Chrony waiting 10 minutes before timing out if it can't reach the NTP server).
> 
> This is fixed in our updates.

Wow, i think you are right.
I installed xcp-ng 8.1 again, and now put my management on my wan interface, and it boots!

How can i update? I tried yum update, but that doesn’t seem to solve the issue.

**Comment by OhSoNoob** [comment]
Yum update did actually put the wait time to about 2 minutes.
Pfsense is running in this machine, which means that the management interface can only reach the internet after the pfsense vm is running.

In 8.0 i can have multiple managment interfaces, but now it seems that i can only have 1, is this true?

Also, another question, is it possible to change BIOS installation to UEFI installation?

**Comment by nagilum99** [comment]
You always, ever, only had one MM-IF. I'm using XS since Version 6.0.
What you can do is add more interfaces for storage. Though, IIRC, they can also be used to be contacted for management, but not being used for all MM functions.

Changing BIOS to UEFI usually needs OS-reinstallation for every OS, since it makes huge differences.
IIRC it's possible to change it without reinstall on Windows, but it requires some work to get it running, so recommendation is: Always reinstall to get a clean system.

**Comment by OhSoNoob** [comment]
> You always, ever, only had one MM-IF. I'm using XS since Version 6.0.
> What you can do is add more interfaces for storage. Though, IIRC, they can also be used to be contacted for management, but not being used for all MM functions.
> 
> Changing BIOS to UEFI usually needs OS-reinstallation for every OS, since it makes huge differences.
> IIRC it's possible to change it without reinstall on Windows, but it requires some work to get it running, so recommendation is: Always reinstall to get a clean system.

Thank you for this clear response.

How can i keep my configuration when reinstalling the OS? I have XOA.

**Comment by nagilum99** [comment]
I've actually never been in the situation with XS/XCP-ng, probably @olivierlambert or someone from Vates has a howto or something for XOA, to backup all stuff.

Important is: You need to boot the install media the same way, you want to boot your OS later on!
I already ran into trouble when testing XCP-ng beta and tried to mix it up to save time. ;-)

**Comment by olivierlambert** [comment]
Indeed, never mix UEFI and BIOS, otherwise the installer won't be able to see previous install. You can export pool metadata via XO (Backup/New/metadata). VM backup is also recommended anyway.

**Comment by OhSoNoob** [comment]
> Indeed, never mix UEFI and BIOS, otherwise the installer won't be able to see previous install. You can export pool metadata via XO (Backup/New/metadata). VM backup is also recommended anyway.

I have a pool metadata and vm backup in XO, but when trying to restore the metadata to a different machine (new installation) it tells me that the machine of the backup can’t be found. Which makes it almost useless.

**Comment by olivierlambert** [comment]
It's made to restore on the same machine IIRC (metadata).

**Comment by OhSoNoob** [comment]
> It's made to restore on the same machine IIRC (metadata).

And what if my boot drive fails?

**Comment by olivierlambert** [comment]
Reinstall and import metadata. That should work. I never really relied on metadata backup on my side, so I have little experience with it.

**Comment by OhSoNoob** [comment]
> Reinstall and import metadata. That should work. I never really relied on metadata backup on my side, so I have little experience with it.

And how do i do that?

**Comment by olivierlambert** [comment]
After your reinstall: in XO, you can import metadata that you have previous backup somewhere. Select the destination pool and it should work.
